services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        env_file:
            - ./secrets/mongo-env.txt
        ports:
            - 27017:27017
        volumes:
            - ./ignored_artifacts:/data/db
